server:
  port: ${SERVER_PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 10
    instance-info-replication-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: '${KEYCLOAK_URI:http://localhost:8180/realms/hrms}'
            user-name-attribute: preferred_username
        registration:
          keycloak-gateway-client:
            provider: keycloak-provider
            client-id: ${CLIENT_ID:hrms-gateway-client}
            client-secret: ${CLIENT_SECRET:IVc0RffM2x2kwC3YWl8Dhd0iHdo1A3P5}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resource-server:
        jwt:
          jwk-set-uri: '${KEYCLOAK_URI:http://localhost:8180/realms/hrms}/protocol/openid-connect/certs'

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: employee-service
          uri:
            lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees/v3/api-docs, /v3/api-docs
            - RewritePath=/employees/actuator, /actuator
            - RewritePath=/employees/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: department-service
          uri:
            lb://department-service
          predicates:
            - Path=/departments/**,/locations/**
          filters:
            - RewritePath=/departments/v3/api-docs, /v3/api-docs
            - RewritePath=/departments/actuator, /actuator
            - RewritePath=/departments/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: job-service
          uri:
            lb://job-service
          predicates:
            - Path=/jobs/**,/contracts/**
          filters:
            - RewritePath=/jobs/v3/api-docs, /v3/api-docs
            - RewritePath=/jobs/actuator, /actuator
            - RewritePath=/jobs/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
logging:
  level:
    org:
      springframework:
        security: info
      springdoc: debug
springdoc:
  swagger-ui:
    urls:
      - name: Employee Service APIs
        url: /v3/api-docs/employees
      - name: Department Service APIs
        url: /v3/api-docs/departments
      - name: Job Service APIs
        url: /v3/api-docs/jobs
    tags-sorter: alpha
    path: /swagger-ui
  default-produces-media-type: "application/json"
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
